function [v_tm, i_tm, v_te, i_te] = get_stratif(k0, krho, er, h_subs, z)
%GET_STRATIF Summary of this function goes here
%   Detailed explanation goes here
    v_tm = NaN( [size(z, 1, 2)] );
    i_tm = NaN( [size(z, 1, 2)] );

    v_te = NaN( [size(z, 1, 2)] );
    i_te = NaN( [size(z, 1, 2)] );

    [v_tm(z > h_subs), i_tm(z > h_subs)] ...
        = get_v_and_i_stratif(k0, krho(z > h_subs), er, h_subs, ...
        z(z > h_subs), 'tm', 'FS');
    [v_tm(z < h_subs), i_tm(z < h_subs)] ...
        = get_v_and_i_stratif(k0, krho(z < h_subs), er, h_subs, ...
        z(z < h_subs), 'tm', 'SUBS');

    [v_te(z > h_subs), i_te(z > h_subs)] ...
        = get_v_and_i_stratif(k0, krho(z > h_subs), er, h_subs, ...
        z(z > h_subs), 'te', 'FS');
    [v_te(z < h_subs), i_te(z < h_subs)] ...
        = get_v_and_i_stratif(k0, krho(z < h_subs), er, h_subs, ...
        z(z < h_subs), 'te', 'SUBS');
end

